config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get "events/index", to: "events#index"#, as: :events_index
  # route to go from home to index
  post "events/index", to: "events#index"

  resources :events, only: [:new, :create, :edit, :update, :destroy, :show] do
    resources :requests, only: [:create, :update]
  end

  resources :requests, only: :destroy
  resources :users, except: [:destroy, :index]
  get "requests/:id/accept/", to: "requests#accept_request", as: "accept_request"
  get "requests/:id/reject/", to: "requests#reject_request", as: "reject_request"

  post "/users/:id/reload", to: "requests#reload", as: "requests_reload"
  post "/users/:id/badge", to: "users#badge", as: "badge_update"

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :users, through: :requests

  validates_presence_of :user_id, :date, :location, :description, :category, :group_size, :name, :group_bio, :group_photo
  validates :description, length: { minimum: 20 }
  validates :category, inclusion: { in: %w[Drinking Sports Games Outdoors Cinema Online] }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  mount_uploader :group_photo, PhotoUploader
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # validates :message, presence: true
  validates :status, inclusion: { in: %w[pending accepted rejected] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests
  # Events that the user created
  has_many :events

  mount_uploader :user_photo, PhotoUploader
  mount_uploader :group_photo, PhotoUploader

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  validates :name, presence: true
  validates :user_bio, presence: true, length: { minimum: 20 }
  # validates :user_photo, presence: true



  # Events that the user has requested to attend
  def events_requested
    requests.map { |request| request.event }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # new_user_registration
  # devise/registrations#new

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_photo, :user_photo_cache, :user_bio, :email, :password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :user_photo, :user_photo_cache, :user_bio])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # require 'open-uri'

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  LOGOS = {
    "Drinking" => "fas fa-beer",
    "Sports" => "fas fa-futbol",
    "Cinema" => "fas fa-film",
    "Games" => "fas fa-chess-king",
    "Online" => "fas fa-laptop",
    "Outdoors" => "fas fa-walking"
}

  def index
    @events = Event.all.reject { |event| event.user == current_user }
    @events = @events.reject { |event| event.requests.select { |request| request.user == current_user}.any? }
    @location = "London"
    if params["data"].present?
      @location = params["data"]["location"] if params["data"]["location"].present?
      @events = Event.near(@location, 3) if params["data"]["location"].present?
      @events = @events.where('date BETWEEN ? AND ?', params["data"]["date"].split(" to ")[0] + " 00:00:00", params["data"]["date"].split(" to ")[1]  + " 23:59:59") if params["data"]["date"].present?
    end
    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude
      }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    # @event.group_photo = current_user.group_photo if params[:event][:group_photo].nil?
    if @event.save
      # current_user.group_photo = @event.group_photo
      # current_user.group_bio = @event.group_bio
      # raise
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @marker = {
        lat: @event.latitude,
        lng: @event.longitude
      }
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location, :description, :category, :group_size, :group_bio, :group_photo)
  end

  def set_event
    if params[:id] == "index"
      redirect_to root_path
    else
      @event = Event.find(params[:id])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :set_request, only: :destroy

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    @request.event = Event.find(params[:event_id])
    if @request.save
      @request.event.user.notifications = true
      @request.event.user.save
      redirect_to user_path(current_user)
    else
      render "events/#{params[:event_id]}"
    end
  end

  def destroy
    @request.destroy
    @user = @request.user
    reload
    # redirect_to user_path(current_user)
  end

  def accept_request
    @request = Request.find(params[:id])
    @request.status = "accepted"
    @request.save
    @request.user.notifications = true
    @request.user.save
    @user = @request.event.user
    reload
    # render "users/show"
  end

  def reject_request
    @request = Request.find(params[:id])
    @request.status = "rejected"
    @request.save
    @request.user.notifications = true
    @request.user.save
    @user = @request.event.user
    reload
    # render "users/show"
  end

  def reload
    @user = User.find(params[:id]) if @user.nil?
    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.js  { render "requests/reload" } # <-- will render `app/views/requests/reload.js.erb`
    end
  end

  private

  def request_params
    params.require(:request).permit(:message)
  end

  def set_request
    @request = Request.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  STATUSES = {
    "pending" => "far fa-clock",
    "accepted" => "fas fa-check",
    "rejected" => "fas fa-times"
  }

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    if @user == current_user
      @user.notifications = false
      @user.save
    end
  end

  def edit
  end

  def update
    photo = @user.user_photo
    @user.update(user_params)
    if @user.user_photo.nil?
      user.user_photo = photo
    end
    redirect_to user_path(@user)
  end

  def badge
    @user = User.find(params[:id])
    respond_to do |format|
      format.js  { render "users/badge" } # <-- will render `app/views/users/badge.js.erb`
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :encrypted_password, :user_bio, :user_photo, :group_bio, :group_photo)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<div class="form-wrapper">
  <div class="event-form-container">
    <div class="form-title">
      <h2>Edit Event</h2>
    </div>
    <%= render 'shared/event-form' %>
  </div>
</div>

<script type="text/javascript">
  flatpickr('.datepicker', {
    altInput: true,
    enableTime: true,
    dateFormat: "Y-m-d H:i",
    defaultDate: new Date,
    minDate: new Date,
    maxDate: new Date().fp_incr(300),
    time_24hr: true
  });
</script>

app/views/events/index.html.erb
<div id="event-index" class="container-lg">
  <div class="event-index-header">
    <h1>Showing <%= @events.size %> events happening near <em><%= @location.capitalize %>:</em></h1>
    <%= render 'shared/search-form' %>
  </div>
  <div class="main-flex">
    <div class="card-container">
      <div class="row">
        <% @events.each do |event| %>
          <div class="col-xs-6">
            <div class="event-card">
              <%= link_to "", event_path(event), class: "divlink" %>
              <div class="card-img" style="background-image: url(<%= image_path event.group_photo.url(:thumbnail) %>)">
              </div>
              <div class="card-info">
                <div class="card-info-header">
                  <span><%= event.name %></span>
                  <i class="<%= EventsController::LOGOS[event.category] %>"></i>
                </div>
                <div class="card-info-body">
                  <div class="card-info-body-l">
                    <p><%= event.user.name.capitalize %> and <%= event.group_size %> friends</p>
                    <p><%= event.location %></p>
                  </div>
                  <div class="card-info-body-r">
                    <p><%= event.date.strftime("%A %d %b") %></p>
                    <p><%= event.date.strftime("%H:%M") %></p>
                  </div>
                </div>
                <%#= link_to "Edit", edit_event_path(event) %>
                <%#= link_to "Delete", event_path(event), method: :delete %>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="map-container">
      <div id="index-map" data-markers="<%= @markers.to_json %>"
      >
      </div>
    </div>
  </div>
</div>

 <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
 <%= javascript_pack_tag "map" %>

app/views/events/new.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<div class="form-wrapper">
  <div class="event-form-container">
    <div class="form-title">
      <h2>New Event</h2>
    </div>
    <%= render 'shared/event-form' %>
  </div>
</div>

<script type="text/javascript">
  flatpickr('.datepicker', {
    altInput: true,
    enableTime: true,
    dateFormat: "Y-m-d H:i",
    defaultDate: new Date,
    minDate: new Date,
    maxDate: new Date().fp_incr(300),
    time_24hr: true
  });
</script>

app/views/events/show.html.erb
<div id="event-show" class="flex-container">
  <div class="event-info-container">
    <div class="event-title-category">
      <h1><%= @event.name %></h1>
      <div class="flex-right">
        <span><%= @event.category.capitalize %></span>
        <i class="<%= EventsController::LOGOS[@event.category] %>"></i>
      </div>
    </div>
    <div class="event-body-flex">
      <div class="event-details-body">
        <div class="event-details-top">
          <p><Strong>Description:</Strong> <%= @event.description %></p>
          <ul>
            <li><strong>Time: </strong><%= @event.date.strftime("%H:%M") %></li>
            <li><strong>Date: </strong><%= @event.date.strftime("%A %d %B %Y") %></li>
            <li><strong>Location: </strong><%= @event.location %></li>
            <li><strong>Group size:</strong> <%= @event.group_size %></li>
            <% unless @event.price.zero? %>
              <li><strong>Price:</strong> £<%= @event.price %> (to cover activity costs)</li>
            <% end %>
          </ul>
        </div>
        <div class="event-details-bottom">
          <p><strong>Host name:</strong> <%= @event.user.name.capitalize %> <%= link_to user_path(@event.user) do%>
            <i class="fas fa-long-arrow-alt-left"></i>
            <span>More about the host</span>
          <% end %>
          </p>
          <p><strong>Group bio:</strong> <%= @event.group_bio %></p>
        </div>
      </div>
      <div class="group-photo" style="background-image: url(<%= image_path @event.group_photo.url(:thumbnail) %>); background-size: cover; background-position: center;">
      </div>
    </div>
    <div class="request-form">
      <%= render 'shared/request-form' %>
    </div>
  </div>
  <div id="map" data-marker="<%= @marker.to_json %>"
    >
  </div>
</div>

 <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
 <%= javascript_pack_tag "map" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Buddy Up</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="<%= "top-margin" if !flash[:alert] %>">
      <%= yield %>
    </div>

    <% if user_signed_in? %>
      <%= form_tag badge_update_path(current_user), method: "post", remote: true do |f| %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <%= submit_tag "", style: "display: none;", id: "badge-reload" %>
      <% end %>
    <% end %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for :data, url: 'events/index', html: { class: 'form-inline' } do |f| %>
  <%= f.input :location, as: :string, input_html: { placeholder: 'Where?' }, wrapper_html: { class: 'form-group' }, label: false %>

  <%= f.input :date, as: :date, wrapper_html: { class: 'form-group' }, label: false, order: [:day, :month, :year] %>
  <div class="form-group">
    <%= f.submit "Go!!", class: 'btn-primary form-control' %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="home-banner">
  <h1>Buddy Up</h1>
  <h3>Find friends wherever you are</h3>
  <%= render 'shared/search-form' %>
</div>


<%#= cl_image_tag User.all[6].user_photo.url(:avatar) %>

app/views/requests/reload.js.erb
dataHosted(`\
  <h2><%= @user.name %>'s Hosted Events</h2>\
  <% @user.events.sort_by { |event| event.date}.each do |event|%>\
    <%= render 'shared/events-requested', event: event, user: @user %>\
  <% end %>\
  `);
dataRequested(`\
  <h2><%= @user.name %>'s Requested Events</h2>\
  <% @user.events_requested.sort_by { |event| event.date}.each do |event| %>\
    <%= render 'shared/events-hosted', event: event, user: @user %>\
  <% end %>\
  `);

app/views/shared/_event-form.html.erb
<div id="event-form">
  <%= simple_form_for @event do |f| %>
    <div id="name-location">
      <div class="form-group-first">
        <%= f.input :name, label: "Event Name", input_html: { placeholder: "e.g. Going to the pub" } %>
        </div>
        <div class="form-group-second">
        <%= f.input :location, label: "Event Location", input_html: { placeholder: "e.g. Hoxton" } %>
        </div>
    </div>
    <div class="inline-form-fields">
      <div class="form-group-first">
        <%= f.input :date, as: :string, input_html: { class: 'datepicker', value: Date.today }, order: [:day, :month, :year], label: "Date & Time"%>
      </div>
      <div class="form-group-second">
        <%= f.input :category, collection: %w[Drinking Sports Games Outdoors Cinema Online] %>
      </div>
    </div>
      <%= f.input :description, label: "Event Description", input_html: { placeholder: "Tell us about the event" }  %>
      <%= f.input :group_bio, as: :text, input_html: { placeholder: "Tell us a bit about your friends" } %>
    <div class="inline-form-fields">
      <div class="form-group-first">
        <%= f.input :group_size, collection: (4...10).to_a.push("10+") %>
        <div >
          <%= f.input :group_photo, label: "New Group Picture?", input_html: { value: current_user.group_photo } %>
          <%= f.input :group_photo_cache, as: :hidden %>
        </div>
      </div>
      <div class="form-group-third" >
        <% unless current_user.group_photo.url.nil? %>
          <p>Current photo</p>
          <div style="background-image: url(<%= image_path current_user.group_photo.url(:thumbnail) %>); background-size: cover; height: 150px;"></div>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Create event", class: ' form-control button-form' %>
    </div>
  <% end %>
</div>

app/views/shared/_event-requests.html.erb
<div class="request-card">
  <div class="card-content-flex">
    <div class="card-left">
      <div class="middle-column">
        <div class="request-title">
          <h4><strong>Request to join from </strong><%= request.user.name %>
          <span class="request-link-sm">
            <%= link_to user_path(request.user), target: "_blank" do%>
              <i class="fas fa-long-arrow-alt-left"></i>
              <span>More about this user</span>
            <% end %>
          </span>
          </h4>
         <p><strong>Message: </strong><%= request.message %></p>
        </div>
      </div>
    </div>
    <div class="request-right">
      <% if request.status == "pending" %>

        <%= form_tag accept_request_path(request), method: :get, remote: true do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
          <%= button_tag :submit, id: "change-request-status", class: "request-confirm" do %>
            <i class="fas fa-check"></i>Confirm request
          <% end %>
        <% end %>

        <%= form_tag reject_request_path(request), method: :get, remote: true do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
          <%= button_tag :submit, id: "change-request-status", class: "request-reject" do %>
            <i class="fas fa-times"></i>Reject request
          <% end %>
        <% end %>

      <% else %>
        <p>Request <%= request.status %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_events-hosted.html.erb
<div class='wide-event-card'>
  <%= link_to event_path(event), class: 'event-card-link' do %>
    <div class='card-content-flex'>
      <div class='card-left'>
        <div class='left-column'><i class='<%= EventsController::LOGOS[event.category] %>'></i>
        </div>
        <div class='middle-column'>
          <div class='wide-event-card-title'>
           <h4><%= event.name %></h4>
          </div>
          <p><%= event.date.strftime('%A %d %b') %> (<%= event.location %>)</p>
          <p><%= event.date.strftime('%H:%M') %></p>
        </div>
      </div>
      <% if user == current_user %>
        <div class='right-column'>
          <div class='request-status <%= event.requests.find { |request| request.user == user }.status %>'>
            <i class='<%= UsersController::STATUSES[event.requests.find { |request| request.user == user }.status] %>'></i>
            <%= event.requests.find { |request| request.user == user }.status %>
          </div>
          <% unless event.requests.find { |request| request.user == user }.status == 'rejected' %>
            <%= form_tag request_path(event.requests.find { |request| request.user == user }), method: :delete, remote: true do |f| %>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              <%= button_tag :submit, id: 'delete-request' do %>
                <i class='fas fa-times'></i>Cancel request
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_events-requested.html.erb
<div class="wide-event-card">
  <%= link_to event_path(event), class: "event-card-link" do %>
    <div class="card-content-flex">
      <div class="card-left">
        <div class="left-column"><i class="<%= EventsController::LOGOS[event.category] %>"></i>
        </div>
        <div class="middle-column">
          <div class="wide-event-card-title">
           <h4><%= event.name %></h4>
          </div>
          <p><%= event.date.strftime("%A %d %b") %> (<%= event.location %>)</p>
          <p><%= event.date.strftime("%H:%M") %></p>
        </div>
      </div>
      <div class="right-column">
        <% if event.requests.select { |request| request.status == "accepted"}.any? %>
          <h4>Event guests</h4>
          <% event.requests.select { |request| request.status == "accepted"}.each do |request| %>
            <p><%= request.user.name %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% if user == current_user %>
  <% event.requests.each do |request| %>
    <%= render 'shared/event-requests', request: request %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-buddy-up">
  <!-- Logo -->
  <%= link_to root_path, class: "buddy-up-logo" do %>
    <%= image_tag "http://www.pngall.com/wp-content/uploads/2018/05/Friends-PNG-File.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-buddy-up-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Create an event", new_event_path , class: "navbar-buddy-up-item navbar-buddy-up-link" %>
      <%= link_to "Profile", user_path(current_user), class: "navbar-buddy-up-item navbar-buddy-up-link" %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-buddy-up-item navbar-buddy-up-link" %>
      <div class="notification-container" id="notification">
          <div class="">
          </div>
          <%= link_to user_path(current_user), class: "navbar-buddy-up-item" do %>
            <%= image_tag current_user.user_photo.url(:avatar), class: "avatar" %>
          <% end %>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-buddy-up-item navbar-buddy-up-link" %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-buddy-up-item navbar-buddy-up-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-buddy-up-item hidden-md hidden-lg">
    <div class="dropdown">
      <% if user_signed_in? %>
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-buddy-up-dropdown-menu">
          <li>
            <%= link_to "Create an event", new_event_path , class: "navbar-buddy-up-item navbar-buddy-up-link" %>
          </li>
          <li>
            <%= link_to "Profile", user_path(current_user), class: "navbar-buddy-up-item navbar-buddy-up-link" %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-buddy-up-item navbar-buddy-up-link" %>
          </li>
        </ul>
      <% else %>
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-buddy-up-dropdown-menu">
          <li>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-buddy-up-item navbar-buddy-up-link" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "navbar-buddy-up-item navbar-buddy-up-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_request-form.html.erb
<% request = Request.new %>
<%= simple_form_for request, url: event_requests_path(@event) do |f| %>
  <%= f.input :message, wrapper_html: { class: 'form-group' }, input_html: { placeholder: 'Message to the host' }, label: false %>
  <%= f.submit "Request to Join", class: 'button form-control'%>
<% end %>

app/views/shared/_search-form.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<div id="search-form">
  <%= simple_form_for :data, url: events_index_path do |f| %>
    <%= f.input :location, as: :string, input_html: { placeholder: 'Where?' }, label: false %>

    <%= f.input :date, as: :string, input_html: { class: 'datepicker', placeholder: "When are you in town?" }, label: false, order: [:day, :month, :year] %>
    <div class="form-group">
      <%= f.submit "Go!!", class: ' form-control button-form' %>
    </div>
  <% end %>
</div>


<script type="text/javascript">
  flatpickr('.datepicker', {
    altInput: true,
    altFormat: "F j, Y",
    dateFormat: "Y-m-d",
    minDate: new Date,
    maxDate: new Date().fp_incr(300),
    mode: "range"
  });
</script>

app/views/users/show.html.erb
<div id="user-show" class="container">
    <div id="middle-bar">
      <div class="tabs">
        <a id="defaultOpen" class="tab" onclick="openEvent(event, 'Joined')">
          <p>Requested events</p>
        </a>
        <a class="tab" onclick="openEvent(event, 'Hosted')">
          <p>Hosted events </p>
        </a>
      </div>
      <div class="white-background">
        <div class="profile-hosted-events tabcontent" id="Hosted">
          <h2><%= @user.name %>'s Hosted Events</h2>
          <% @user.events.sort_by { |event| event.date}.each do |event|%>
            <%= render 'shared/events-requested', event: event, user: @user %>
          <% end %>
        </div>
        <div class="profile-joined-events tabcontent" id="Joined">
          <h2><%= @user.name %>'s Requested Events</h2>
          <% @user.events_requested.sort_by { |event| event.date}.each do |event| %>
            <%= render 'shared/events-hosted', event: event, user: @user %>
          <% end %>
        </div>
      </div>
    </div>
  <div id="user-info">
    <div class="user-photo" style="background-image: url(<%= @user.user_photo %>); background-size: cover; background-position: center;">
    </div>
    <h1><%= @user.name %>'s page</h1>
    <h4>User Bio:</h4>
    <p><%= @user.user_bio %></p>
    <%= link_to "edit profile", edit_user_path(@user), class: "form-container-two" %>
  </div>
</div>

<%= form_tag requests_reload_path(@user), method: "post", remote: true do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <%= submit_tag "", style: "display: none;", id: "reload" %>
<% end %>

<script type="text/javascript">

  const reloadButton = document.getElementById("reload");

  const reloadPage = () => {
    reloadButton.click()
  };

  document.addEventListener("DOMContentLoaded", (event) => {
    setInterval(reloadPage, 10000)
  });


  const dataHosted = (content) => {
    const element = document.getElementById('Hosted')
    element.innerHTML = content;
  }

  const dataRequested = (content) => {
    const element = document.getElementById('Joined')
    element.innerHTML = content;
  }


  function openEvent(evt, eventName) {
    // Declare all variables
    var i, tabcontent, tab;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tab" and remove the class "active"
    tab = document.getElementsByClassName("tab");
    for (i = 0; i < tab.length; i++) {
        tab[i].className = tab[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the button that opened the tab
    document.getElementById(eventName).style.display = "block";
    evt.currentTarget.className += " active";
  }

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>